### PR TITLE
Pointcloud noise suppression

### PR DESCRIPTION
**Pull request by nicovanduijn**
This is simply a rebase of #289, it should consider histogram cells free if they don't contain a minimum number of points, defined by the parameter `min_num_points_per_cell_`.

We will test-fly this soon. Attempting to solve #309 

@sunzj Can you test if this works for you?

### CODE REVIEW

**Comment by sunzj** [comment]
@nicovanduijn as I said in https://github.com/PX4/avoidance/issues/309, the noise suppression is important for Realsense R200. 

Test outdoor, without noise suppression, the drone will stop even if there isn't any obstacle.

**Comment by LorenzMeier** [comment]
@jkflying Please make sure we do suppress noise for all models, not just for the R200. Vision is never 100% accurate and I don't want to build a solution that deteriorates quickly in performance if the sensors are not perfect or the lighting is suboptimal.

**Comment by nicovanduijn** [comment]
We need this capability for sure. The challenge will be finding a suppression level that works reasonably well for all models. I would suggest having the default values tuned to the most commonly used sensor, leaving individual tuning to each user

**Comment by nicovanduijn** [comment]
We had successful flight tests with this.The default noise suppression level is set to a good value for SITL (1 pt/cell), since SITL is what most people use.

As to reasonable noise suppression levels on real flights, we have so far tested 25 pts/cell with an intel RealSense D435 and achieved pretty good results. We will test increasing it a bit more, but that should not be a blocker for this PR.

I added a sample config yaml file for real flights for convenience.

LGTM

**Pull request merged**
