### PR TITLE
add fancy marker for range scan

### PR DESCRIPTION
**Pull request by baumanta**

### CODE REVIEW

**Comment by mhkabir** [comment]
@baumanta would you be able to post a screenshot of what this looks like? :)

**Comment by baumanta** [comment]
range_scan

**Comment by baumanta** [comment]
@mhkabir  here you go :) It is just a visualization of the range scan message, which basically is a 1D histogram compression. This goes to the FCU as OBSTACLE_DISTANCE message and is used for collision prevention.

**Comment by mhkabir** [comment]
Thanks, this looks great!

**Pull request merged**
