### PR TITLE
Global Planner: update obstacle avoidance interface

### PR DESCRIPTION
**Pull request by mrivi**
This PR brings the new obstacle avoidance interface on the global planner

### CODE REVIEW

**Comment by nicovanduijn** [comment]
I tried this, but somehow it never advances to the first mission item after takeoff. Similar to the corner case we found with the local planner, but more consistent. Do you experience this too?

**Comment by mrivi** [comment]
I'll look into it

**Comment by mhkabir** [comment]
Hey guys, @nicovanduijn @mrivi. Do either of you plan to have a look at this soon?

**Comment by nicovanduijn** [comment]
I've been using it in SITL and it works just fine. I'm not doing any actual flight testing these days, so I can't do that.

Not sure if this is a priority for @mrivi or @baumanta, but it would of course be nice to support the global planner again at some point

**Comment by mhkabir** [comment]
Is the mission getting stuck issue still present with the latest Firmwares changes?

**Comment by mrivi** [comment]
@mhkabir no, it's solved

**Comment by LorenzMeier** [comment]
@baumanta @mrivi What is the status of this PR?

**Comment by mrivi** [comment]
@LorenzMeier it has been used in simulation by @nicovanduijn for his thesis but it has never been tested on hardware

**Comment by nicovanduijn** [comment]
I think we should merge this. 

The global planner hasn't been flight-tested in so long that without this, it won't even be testable (using the offboard & RViz is just a pain), and this pr at least brings it into a state that works in SITL and is somewhat in sync with the local planner in terms of the interface.

LGTM

**Pull request merged**
