### PR TITLE
Integrate rvizworld loader into global planner

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR implements rvizworldloader into the global planner, to enable global planner be tested in the same environment as the local planner.

- Integrate rvizworld loader into `path_handler_node` in `global_planner`
- Unified `globalplanner_sitl_mavros.launch` and `localplanner_sitl_mavros.launch` into `avoidance_sitl_mavros.launch`
- A few modifications that follow better the local_planner conventions in global planner launch files
- Moved sim directory under avoidance package
- Updated rviz config

In an attempt to do this cleaner, the sim directory was moved into the common avoidance pkg.
Previously:
```
    <include file="$(find local_planner)/../sim/world/..." >
```
Now:
```
    <include file="$(find avoidance)/sim/world/..." >
```
This can be tested with the global_planner_stereo.launch
```
roslaunch global_planner global_planner_stereo.launch
```

Other launchfiles needs more work, but this seems appropriate enough for now

57361350-869f9700-717c-11e9-90db-db8cbe577678

### CODE REVIEW

**Comment by jkflying** [comment]
Have you tested all of the launch files? We don't have any CI to make sure they are still working, so I want to be extra careful here.

**Comment by Jaeyoung-Lim** [comment]
@jkflying For the `local_planner` no, I have tested the following launchfiles and it is functional. 
- `local_planner_sitl_3cam.launch`
- `local_planner_stereo.launch`
However, I am not sure about the rest of the launchfiles as I couldn't run all launchfiles successfully such as the `local_planner_realsense.launch`
Am I missing something?

For the global_planner, also no. Part of the reason is that all launchfiles in global_planner is not functional. Therefore, only the `global_planner_stereo.launch` will use the changes in this PR. If it is okay, I would like to clean up the launchfiles in the `global_planner` in a separate PR and depricate outdated launchfiles all together

**Comment by jkflying** [comment]
Hmm, on my system this PR isn't working. I've tried `local_planner_sitl_3cam.launch` and `local_planner_depth-camera.launch`. I tried a `make clean` and re-sourcing the `setup.sh`. 

The last output I see is 
`[INFO] [1557824966.378516, 0.060000]: Calling service /gazebo/spawn_sdf_model`

and then every 30 seconds the failed requests to get params:
```
[ERROR] [1557825190.411810735, 0.312000000]: PR: Unknown parameter to get: MPC_XY_CRUISE
[ERROR] [1557825190.413111125, 0.312000000]: PR: Unknown parameter to get: MPC_COL_PREV_D
```
And then finally the planner abort
```
[INFO] [1557825227.918693, 10.180000]: Spawn status: SpawnModel: Entity pushed to spawn queue, but spawn service timed out waiting for entity to appear in simulation under the name iris
[spawn_model-7] process has finished cleanly
log file: /home/julian/.ros/log/6baad526-7628-11e9-8d6f-0c5415acc1f5/spawn_model-7*.log
[ WARN] [1557825232.992258155, 15.248000000]:  Planner abort: missing required data 
 
[ WARN] [1557825232.992373941, 15.252000000]: ----------------------------- Debugging Info -----------------------------
[ WARN] [1557825232.992399517, 15.252000000]: Local planner has not received a position from FCU, check the following: 
[ WARN] [1557825232.992419566, 15.252000000]: 1. Check cables connecting PX4 autopilot with onboard computer
[ WARN] [1557825232.992446798, 15.252000000]: 2. Set PX4 parameter MAV_1_MODE to onbard or external vision
[ WARN] [1557825232.992465315, 15.252000000]: 3. Set correct fcu_url in local_planner launch file:
[ WARN] [1557825232.992485635, 15.252000000]:    Example direct connection to serial port: /dev/ttyUSB0:921600
[ WARN] [1557825232.992504511, 15.252000000]:    Example connection over mavlink router: udp://:14540@localhost:14557
[ WARN] [1557825232.992523918, 15.252000000]: --------------------------------------------------------------------------
```

**Comment by Jaeyoung-Lim** [comment]
@jkflying Any chance that your 'GAZEBO_MODEL_PATH` is using the old one?

I have also updated the readme for this

**Comment by jkflying** [comment]
My bad, I missed that. All working now :+1:

**Pull request merged**
