### PR TITLE
enable COM_OBS_AVOID by default

### PR DESCRIPTION
**Pull request by mrivi**
For the lazy people :)

### CODE REVIEW

**Comment by nicovanduijn** [comment]
Wouldn't this require https://github.com/PX4/sitl_gazebo/pull/300 to be merged?

**Comment by mrivi** [comment]
No, this is enough https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/init.d-posix/1015_iris_obs_avoid

**Comment by nicovanduijn** [comment]
So, there is no sdf model file for the iris_obs_avoid?

**Comment by mrivi** [comment]
The vehicle being loaded is still the one in the avoidance models folder. I just want to load the iris default PX4 parameters plus `COM_OBS_AVOID` to 1 which is in set in that ROMFS script

**Pull request merged**
