### PR TITLE
Fix tf exception

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
After #430, `global_planner` fails with the following error.
```
terminate called after throwing an instance of 'tf2::LookupException'
  what():  "map" passed to lookupTransform argument source_frame does not exist.
```

This PR gets rid of unneeded tf listeners to prevent this happening again. The error was introduced as mavros config changed its `frame_id`s for some frames.

### CODE REVIEW

**Comment by nicovanduijn** [comment]
looks like a no-brainer.
LGTM

**Comment by Jaeyoung-Lim** [comment]
@nicovanduijn Can we merge this since `global_planner` is broken in master

**Comment by mrivi** [comment]
@Jaeyoung-Lim is the `world` frame used anywhere in the global planner? Otherwise we can also remove https://github.com/PX4/avoidance/blob/master/global_planner/launch/global_planner_depth-camera.launch#L12-L13

**Comment by Jaeyoung-Lim** [comment]
@mrivi Maybe no longer after this PR. I will do a check

**Comment by Jaeyoung-Lim** [comment]
@mrivi Removed the static tf publishers!

**Pull request merged**
