### PR TITLE
Initialize node handle in main function

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR initializes the node handle in the main function.

This enables multiple objects to consume node handle within the local planner object in the constructor.

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
Rebased

**Comment by jkflying** [comment]
I'm trying to run a rebased version in SITL but it won't start. Can you take a look?

**Comment by Jaeyoung-Lim** [comment]
@jkflying It seems like the change of the `node handle` name space broke subscribing to the correct topics. I have made a fix.

**Comment by jkflying** [comment]
I've rebased this, but I'm still getting the same error as before, the avoidance system won't start on SITL :confused: Give me a ping, let's discuss what's happening here.

**Comment by Jaeyoung-Lim** [comment]
@jkflying The refactor on the `dynamic_reconfigure` was causing the problem. I have made a fix. I will try to look more into what is going on with the `dynamic_reconfigure`

**Comment by Jaeyoung-Lim** [comment]
Also tested in SITL, works as normal!

**Pull request merged**
