### PR TITLE
Remove mav_msgs dependency

### PR DESCRIPTION
**Pull request by mhkabir**
Unused dependency.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Thanks!

**Comment by nicovanduijn** [comment]
Pretty sure it's gonna be required for #76, but until we decide to merge it this is fine

**Comment by mhkabir** [comment]
@nicovanduijn What is it needed for specifically?

**Comment by nicovanduijn** [comment]
I could be wrong about whether the dependency is actually needed or not. All I know is the mission interface uses the trajectory message  defined in ```mavros_msgs/Trajectory.h```  on the topics ```/mavros/trajectory/desired``` and ```/mavros/trajectory/generated```. Am I mixing something up?

**Comment by mhkabir** [comment]
Yeah. That's `mavros_msgs`. `mav_msgs` is an old dependency from the `rotors_simulator` days.

**Comment by nicovanduijn** [comment]
my bad, didn't read properly

**Pull request merged**
