### PR TITLE
ReadMe: Mavros has to be installed from sources

### PR DESCRIPTION
**Pull request by baumanta**

### CODE REVIEW

**Comment by TSC21** [comment]
@baumanta it has to in the next couple of weeks probably. After that, this isn't applicable anymore since the MAVROS will already have a release.

**Comment by baumanta** [comment]
@TSC21 somebody had problems because they tried to install the package. I think in general it might probably be good to recommend installing from sources as the avoidance is still under development and we might have to add new messages and do not want to break it for everybody when we do. But it might not happen very often. What do you think is better?

What do you think @hamishwillee ?

**Comment by mrivi** [comment]
I have asked @LorenzMeier if he can ask for a new mavros release since last one (v 0.27.0) was on November 12.

**Comment by hamishwillee** [comment]
@TSC21 @mrivi Good points, good action. That said, I hate waiting on things that might not happen in a timely manner. Consider adding a note, and removing following the release.

> **Note:** MAVROS release 0.27.0 is incompatible with this software. A new release is expected imminently, but in the meantime install from sources.

Entirely up to you.

**Comment by mrivi** [comment]
MAVROS release 0.28.0 is out, closing this

**Pull request closed without merging**
