### PR TITLE
[GlobalPlanner] Deprecate launchfiles and update readme

### PR DESCRIPTION
**Pull request by Jaeyoung-Lim**
This PR deprecates launchfiles that are unused / obsolete in the global_planner, and update the README accordingly

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
@mrivi I am not sure if it had it before.

I can definitely add it if we need it. I was working on supporting multicam for the global planner, so might make sense to do it together.

**Comment by mrivi** [comment]
@Jaeyoung-Lim no, it was using iris_depth_camera
https://github.com/PX4/avoidance/blob/9f94443b5f4e20660c83b916f8d31a95cd563a37/global_planner/launch/global_planner_sitl_mavros.launch#L10

**Comment by Jaeyoung-Lim** [comment]
@mrivi Ah, okay  I was confused with this:

https://github.com/PX4/avoidance/blob/9f94443b5f4e20660c83b916f8d31a95cd563a37/global_planner/launch/global_planner_sitl_mavros.launch

I will create a separate PR for the depth camera!

**Comment by mrivi** [comment]
Thanks!

**Pull request merged**
